window.COURSE_CONFIG = {

  title: 'C++ for Drone Engineering',
  icon: '🚁',
  subtitle: 'Ubuntu 24.04 · ROS2 Jazzy · ArduPilot SITL · C++17',
  footer: 'C++ for Drone Engineering · v1.0 · April 2026',
  stateKey: 'drone_course_state',

  description: 'A complete course from zero to job-ready portfolio. Developers with any programming background.',
  prerequisites: [
    'Any programming language',
    'Linux command line basics',
    'Ubuntu 24.04 installed',
  ],
  timeCommitment: '8–9 hrs/week · ~3 months to portfolio',
  goal: 'Write real ROS2 drone software in C++ with a GitHub portfolio',

  modules: [
    {
      id: 's1',
      num: '1',
      title: 'Understanding the Drone Software Stack',
      tag: 'Read first',
      tagColor: 'blue',
      file: 'module-1.html',
    },
    {
      id: 's2',
      num: '2',
      title: 'Environment Setup',
      tag: 'Do first',
      tagColor: 'green',
      file: 'module-2.html',
    },
    {
      id: 's25',
      num: '2.5',
      title: 'C Fundamentals Refresher',
      tag: 'Skip if confident',
      tagColor: 'orange',
      file: 'module-2-5.html',
    },
    {
      id: 's3',
      num: '3',
      title: 'C++ Fundamentals for Drone Development',
      tag: 'Core skill',
      tagColor: 'blue',
      file: 'module-3.html',
    },
    {
      id: 's4',
      num: '4',
      title: 'Understanding ROS2',
      tag: 'Core framework',
      tagColor: 'purple',
      file: 'module-4.html',
    },
    {
      id: 's5',
      num: '5',
      title: 'First ROS2 Node in C++',
      tag: 'Memorize this',
      tagColor: 'blue',
      file: 'module-5.html',
    },
    {
      id: 's6',
      num: '6',
      title: 'Portfolio Projects',
      tag: '4 projects',
      tagColor: 'green',
      file: 'module-6.html',
    },
    {
      id: 's7',
      num: '7',
      title: 'Reading Real Drone Code',
      tag: 'Month 3+',
      tagColor: 'amber',
      file: 'module-7.html',
    },
    {
      id: 's8',
      num: '8',
      title: 'Open Source Contributions',
      tag: 'Portfolio booster',
      tagColor: 'purple',
      file: 'module-8.html',
    },
    {
      id: 's9',
      num: '9',
      title: 'Milestones and Schedule',
      tag: 'Track progress',
      tagColor: 'green',
      file: 'module-9.html',
    },
    {
      id: 's10',
      num: '10',
      title: 'Key Resources and Error Reference',
      tag: 'Quick reference',
      tagColor: 'blue',
      file: 'module-10.html',
    },
  ],

  numColors: {
    s1:  'background:#eff6ff;color:#1d4ed8;',
    s2:  'background:#f0fdf4;color:#16a34a;',
    s25: 'background:#fff7ed;color:#c2410c;',
    s3:  'background:#eff6ff;color:#1d4ed8;',
    s4:  'background:#f3e8ff;color:#6b21a8;',
    s5:  'background:#eff6ff;color:#1d4ed8;',
    s6:  'background:#f0fdf4;color:#16a34a;',
    s7:  'background:#fef3c7;color:#92400e;',
    s8:  'background:#f3e8ff;color:#6b21a8;',
    s9:  'background:#f0fdf4;color:#16a34a;',
    s10: 'background:#eff6ff;color:#1d4ed8;',
  },

}
